/* *********************************** */
/*          Author: rng70              */
/*                                     */
/*  This program is to blink the led   */
/*  at PIND6. To do so, a hex file is  */
/*  can be generated by compiling the  */
/*         file in Arduino IDE         */
/*                                     */
/* *********************************** */

/* *********************************** */
/*     Map the PIN connection of       */
/* ATmega32 with the PIN connection of */
/*              Arduino                */
/* *********************************** */

const int pA0 = 31;
const int pA1 = 30;
const int pA2 = 29;
const int pA3 = 28;
const int pA4 = 27;
const int pA5 = 26;
const int pA6 = 25;
const int pA7 = 24;

const int pB0 = 0;
const int pB1 = 1;
const int pB2 = 2;
const int pB3 = 3;
const int pB4 = 4;
const int pB5 = 5;
const int pB6 = 6;
const int pB7 = 7;

const int pC0 = 16;
const int pC1 = 17;
const int pC2 = 18;
const int pC3 = 19;
const int pC4 = 20;
const int pC5 = 21;
const int pC6 = 22;
const int pC7 = 23;

const int pD0 = 8;
const int pD1 = 9;
const int pD2 = 10;
const int pD3 = 11;
const int pD4 = 12;
const int pD5 = 13;
const int pD6 = 14;
const int pD7 = 15;

int LED_PIN = pD6;

void setup() {
  /* initialize digital pin LED_PIN as an output */
  pinMode(LED_PIN, OUTPUT);
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(LED_PIN, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(1000);                       // wait for a second
  digitalWrite(LED_PIN, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);                       // wait for a second
}
